version: '3.7'

services:
    currency-exchange:
        image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8000:8000"
          
    currency-conversion:
        image: in28min/mmv2-currency-conversion:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8100:8100"
          
    gateway:
        image: in28min/mmv2-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8765:8765"
          
    naming-server:
        image: in28min/mmv2-naming-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8761:8761"